default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # git state
      - id: check-merge-conflict
      - id: check-added-large-files
      # common file problems
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: check-symlinks
      - id: destroyed-symlinks
      # language specific checks
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
