---
matchers:
  - pattern: ^.+\.(js|css|svg)$
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: true
  - pattern: ^.+\.(png|jpg|webp)$
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: false
  - pattern: ^.+\.(mp4|webm)$
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: false
  - pattern: ^sitemap\.xml$
    contentType: application/xml
    gzip: true
  - pattern: ^.+\.(html|xml|json)$
    gzip: true
