---
name: 👷 Continuous Integration

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["master"]

jobs:
  ci:
    uses: wrboyce/github-workflows/.github/workflows/hugo-ci.yaml@master
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
